# Generated by Django 4.1.1 on 2022-09-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
