# Generated by Django 4.1.1 on 2022-09-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
