# Generated by Django 4.1.1 on 2022-09-09 16:26

import api.post.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForkedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(null=True)),
                ('Created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRstatus', models.BooleanField(default=None, null=True)),
                ('ForkID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.forkedpost')),
                ('FromUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromUser', to=settings.AUTH_USER_MODEL)),
                ('ToUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(null=True)),
                ('PostType', models.CharField(max_length=15)),
                ('CodeBlock', models.TextField(blank=True, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('CodeSnippet', models.TextField(blank=True, null=True)),
                ('CodeLanguage', models.CharField(max_length=15)),
                ('Created_at', models.DateTimeField()),
                ('GroupId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-Created_at'],
            },
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_at', models.DateTimeField()),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('UserID', models.ForeignKey(on_delete=models.SET(api.post.models.get_deleted), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='forkedpost',
            name='PostID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
        migrations.AddField(
            model_name='forkedpost',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField()),
                ('isAReply', models.BooleanField(default=False)),
                ('Vote', models.PositiveIntegerField(default=0)),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('ReplyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.commentpost')),
                ('UserID', models.ForeignKey(on_delete=models.SET(api.post.models.get_deleted), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
