# Generated by Django 4.1.1 on 2022-09-09 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('PullRequestID', models.AutoField(primary_key=True, serialize=False)),
                ('PRstatus', models.BooleanField(default=None, null=True)),
                ('ForkID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.forkedpost')),
                ('FromUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromUser', to=settings.AUTH_USER_MODEL)),
                ('ToUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
