# Generated by Django 4.1.1 on 2022-09-09 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_commentpost_replyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='ReplyID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replyid', to='post.commentpost'),
        ),
    ]
