# Generated by Django 4.1.1 on 2022-09-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_pullrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='CodeBlock',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='CodeSnippet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
